import { createAction } from 'redux-actions';

export const REQUEST_ADMIN_ORDERS = createAction('REQUEST_ADMIN_ORDERS');
export const REQUEST_ADMIN_ORDERS_SUCCESS = createAction('REQUEST_ADMIN_ORDERS_SUCCESS');
export const REQUEST_ADMIN_ORDERS_FAILED = createAction('REQUEST_ADMIN_ORDERS_FAILED');

export const REQUEST_ADMIN_PRODUCTS = createAction('REQUEST_ADMIN_PRODUCTS');
export const REQUEST_ADMIN_PRODUCTS_SUCCESS = createAction('REQUEST_ADMIN_PRODUCTS_SUCCESS');
export const REQUEST_ADMIN_PRODUCTS_FAILED = createAction('REQUEST_ADMIN_PRODUCTS_FAILED');

export const CREATE_PRODUCT = createAction('CREATE_PRODUCT');
export const CREATE_PRODUCT_SUCCESS = createAction('CREATE_PRODUCT_SUCCESS');
export const CREATE_PRODUCT_FAILED = createAction('CREATE_PRODUCT_FAILED');

export const UPDATE_PRODUCT = createAction('UPDATE_PRODUCT');
export const UPDATE_PRODUCT_SUCCESS = createAction('UPDATE_PRODUCT_SUCCESS');
export const UPDATE_PRODUCT_FAILED = createAction('UPDATE_PRODUCT_FAILED');

export const REQUEST_SINGLE_PRODUCT = createAction('REQUEST_SINGLE_PRODUCT');
export const REQUEST_SINGLE_PRODUCT_SUCCESS = createAction('REQUEST_SINGLE_PRODUCT_SUCCESS');
export const REQUEST_SINGLE_PRODUCT_FAILED = createAction('REQUEST_ADMIN_PRODUCT_FAILED');

export const DELETE_PRODUCT = createAction('DELETE_PRODUCT');
export const DELETE_PRODUCT_SUCCESS = createAction('DELETE_PRODUCT_SUCCESS');
export const DELETE_PRODUCT_FAILED = createAction('DELETE_PRODUCT_FAILED');
